-- AlterEnum: add USER to NotificationType
ALTER TABLE `notifications` MODIFY `type` ENUM('APPOINTMENT', 'INSURANCE', 'PAYMENT', 'SUPPORT', 'SYSTEM', 'CHAT', 'LAB_RESULT', 'PRESCRIPTION', 'REPORT', 'REVIEW', 'VERIFICATION', 'USER') NOT NULL;
